d:
cd d:\rhugh\Documents\CTU_Doctoral\Dissertation\Source\BMA_Dissertation\BMA_Dissertation

rem usage: python BMA_Dissertation.py file_path weight_column averagepercision_column sheet_name outputfile(.csv) imagefile(file format: eg: jpg)
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "Weight Average" "Video" "Ye2024 Video Data" "Ye2024_Video.csv" "Ye2024_Video.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "Weight Average" "Image" "Ye2024 Image Data" "Ye2024_Image.csv" "Ye2024_Image.jpg"

python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "AP Basic" "AP 0.5" "Borkman2021" "Borkman2021_AP05.csv" "Borkman2021_AP05.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "AP Basic" "AR 100" "Borkman2021" "Borkman2021_AR100.csv" "Borkman2021_AR100.jpg"

python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "After fine Tuning" "AP Box" "Borrego2018" "Borrego2018_APBox.csv" "Borrego2018_APBox.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "After fine Tuning" "AP Cylinder" "Borrego2018" "Borrego2018_APCylinder.csv" "Borrego2018_APCylinder.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "After fine Tuning" "AP Sphere" "Borrego2018" "Borrego2018_APSphere.csv" "Borrego2018_APSphere.jpg"

python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "AP Box" "Borrego_2_2018" "Borrego2018_2_APBox.csv" "Borrego2018_2_APBox.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "AP Cylinder" "Borrego_2_2018" "Borrego2018_2_APCylinder.csv" "Borrego2018_2_APCylinder.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "AP Sphere" "Borrego_2_2018" "Borrego2018_2_APSphere.csv" "Borrego2018_2_APSphere.jpg"

python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "General Image" "Type A Aircraft" "Clement2024" "Clement2024_AAircraft.csv" "Clement2024_AAircraft.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "General Image" "Type B Aircraft" "Clement2024" "Clement2024_BAircraft.csv" "Clement2024_BAircraft.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "General Image" "All Rail" "Clement2024" "Clement2024_ARail.csv" "Clement2024_ARail.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "General Image" "Passenger" "Clement2024" "Clement2024_Passenger.csv" "Clement2024_Passenger.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "General Image" "Tanker" "Clement2024" "Clement2024_Tanker.csv" "Clement2024_Tanker.jpg"

python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "Average" "aero" "Dvornik2018" "Dvornik2018_aero.csv" "Dvornik2018_aero.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "Average" "bike" "Dvornik2018" "Dvornik2018_bike.csv" "Dvornik2018_bike.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "Average" "boat" "Dvornik2018" "Dvornik2018_boat.csv" "Dvornik2018_boat.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "Average" "bott" "Dvornik2018" "Dvornik2018_bott.csv" "Dvornik2018_bott.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "Average" "bus" "Dvornik2018" "Dvornik2018_bus.csv" "Dvornik2018_bus.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "Average" "car" "Dvornik2018" "Dvornik2018_car.csv" "Dvornik2018_car.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "Average" "cat" "Dvornik2018" "Dvornik2018_cat.csv" "Dvornik2018_cat.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "Average" "chair" "Dvornik2018" "Dvornik2018_chair.csv" "Dvornik2018_chair.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "Average" "cow" "Dvornik2018" "Dvornik2018_cow.csv" "Dvornik2018_cow.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "Average" "table" "Dvornik2018" "Dvornik2018_table.csv" "Dvornik2018_table.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "Average" "dog" "Dvornik2018" "Dvornik2018_dog.csv" "Dvornik2018_dog.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "Average" "horse" "Dvornik2018" "Dvornik2018_horse.csv" "Dvornik2018_horse.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "Average" "motorbike" "Dvornik2018" "Dvornik2018_motorbike.csv" "Dvornik2018_motorbike.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "Average" "person" "Dvornik2018" "Dvornik2018_person.csv" "Dvornik2018_person.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "Average" "plan" "Dvornik2018" "Dvornik2018_plan.csv" "Dvornik2018_plan.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "Average" "sheep" "Dvornik2018" "Dvornik2018_sheep.csv" "Dvornik2018_sheep.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "Average" "sofa" "Dvornik2018" "Dvornik2018_sofa.csv" "Dvornik2018_sofa.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "Average" "train" "Dvornik2018" "Dvornik2018_train.csv" "Dvornik2018_train.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "Average" "tv" "Dvornik2018" "Dvornik2018_tv.csv" "Dvornik2018_tv.jpg"

python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "Coca Cola" "Dwibedi2017" "Dwibedi2017_cocacola.csv" "Dwibedi2017_cocacola.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "Coffeemate" "Dwibedi2017" "Dwibedi2017_coffeemate.csv" "Dwibedi2017_coffeemate.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "Honey Bunches" "Dwibedi2017" "Dwibedi2017_honeybunches.csv" "Dwibedi2017_honeybunches.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "Hunt's Sauce" "Dwibedi2017" "Dwibedi2017_huntsauce.csv" "Dwibedi2017_huntsauce.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "Mahama Rice" "Dwibedi2017" "Dwibedi2017_mahamarice.csv" "Dwibedi2017_mahamarice.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "nature v1" "Dwibedi2017" "Dwibedi2017_naturev1.csv" "Dwibedi2017_naturev1.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "nature v2" "Dwibedi2017" "Dwibedi2017_naturev2.csv" "Dwibedi2017_naturev2.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "Palmolive orange" "Dwibedi2017" "Dwibedi2017_palmoliveorange.csv" "Dwibedi2017_palmoliveorange.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "pop secret" "Dwibedi2017" "Dwibedi2017_popsecret.csv" "Dwibedi2017_popsecret.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "pringles bbq" "Dwibedi2017" "Dwibedi2017_pringlebbq.csv" "Dwibedi2017_pringlebbq.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "Redbull" "Dwibedi2017" "Dwibedi2017_redbull.csv" "Dwibedi2017_redbull.jpg"

python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "AP" "MODA" "Fabbri2021" "Fabbri2021.csv" "Fabbri2021.jpg"

python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "Coca Cola" "Ge2023" "Ge2023_cocacola.csv" "Ge2023_cocacola.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "Coffeemate" "Ge2023" "Ge2023_coffeemate.csv" "Ge2023_coffeemate.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "Honey Bunches" "Ge2023" "Ge2023_honeybunches.csv" "Ge2023_honeybunches.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "Hunt's Sauce" "Ge2023" "Ge2023_huntsauce.csv" "Ge2023_huntsauce.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "Mahama Rice" "Ge2023" "Ge2023_mahamarice.csv" "Ge2023_mahamarice.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "nature v1" "Ge2023" "Ge2023_naturev1.csv" "Ge2023_naturev1.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "nature v2" "Ge2023" "Ge2023_naturev2.csv" "Ge2023_naturev2.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "Palmolive orange" "Ge2023" "Ge2023_palmoliveorange.csv" "Ge2023_palmoliveorange.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "pop secret" "Ge2023" "Ge2023_popsecret.csv" "Ge2023_popsecret.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "pringles bbq" "Ge2023" "Ge2023_pringlebbq.csv" "Ge2023_pringlebbq.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "Redbull" "Ge2023" "Ge2023_redbull.csv" "Ge2023_redbull.jpg"

python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "Coca Cola" "Georgakis2017" "Georgakis2017_cocacola.csv" "Georgakis2017_cocacola.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "Coffeemate" "Georgakis2017" "Georgakis2017_coffeemate.csv" "Georgakis2017_coffeemate.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "Honey Bunches" "Georgakis2017" "Georgakis2017_honeybunches.csv" "Georgakis2017_honeybunches.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "Hunt's Sauce" "Georgakis2017" "Georgakis2017_huntsauce.csv" "Georgakis2017_huntsauce.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "Mahama Rice" "Georgakis2017" "Georgakis2017_mahamarice.csv" "Georgakis2017_mahamarice.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "nature v1" "Georgakis2017" "Georgakis2017_naturev1.csv" "Georgakis2017_naturev1.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "nature v2" "Georgakis2017" "Georgakis2017_naturev2.csv" "Georgakis2017_naturev2.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "Palmolive orange" "Georgakis2017" "Georgakis2017_palmoliveorange.csv" "Georgakis2017_palmoliveorange.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "pop secret" "Georgakis2017" "Georgakis2017_popsecret.csv" "Georgakis2017_popsecret.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "pringles bbq" "Georgakis2017" "Georgakis2017_pringlebbq.csv" "Georgakis2017_pringlebbq.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "Redbull" "Georgakis2017" "Georgakis2017_redbull.csv" "Georgakis2017_redbull.jpg"

python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "AP50" "Heindl2020" "Heindl2020_ap50.csv" "Heindl2020_ap50.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "Ap75" "Heindl2020" "Heindl2020_ap75.csv" "Heindl2020_ap75.jpg"

python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "AP-Cotton" "Hu2021" "Hu2021_cotton.csv" "Hu2021_cotton.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "AP-Morningglory" "Hu2021" "Hu2021_morningglory.csv" "Hu2021_morningglory.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "AP-Grass" "Hu2021" "Hu2021_grass.csv" "Hu2021_grass.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "AP-Other" "Hu2021" "Hu2021_other.csv" "Hu2021_other.jpg"

python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "one" "Hughes2021" "Hughes2021_1.csv" "Hughes2021_1.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "two" "Hughes2021" "Hughes2021_2.csv" "Hughes2021_2.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "three" "Hughes2021" "Hughes2021_3.csv" "Hughes2021_3.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "four" "Hughes2021" "Hughes2021_4.csv" "Hughes2021_4.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "five" "Hughes2021" "Hughes2021_5.csv" "Hughes2021_5.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "six" "Hughes2021" "Hughes2021_6.csv" "Hughes2021_6.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "seven" "Hughes2021" "Hughes2021_7.csv" "Hughes2021_7.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "eight" "Hughes2021" "Hughes2021_8.csv" "Hughes2021_8.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "nine" "Hughes2021" "Hughes2021_9.csv" "Hughes2021_9.jpg"

python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "Easy" "Moderate" "Kar2019" "Kar2019_EModerate.csv" "Kar2019_EModerate.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "Easy" "Hard" "Kar2019" "Kar2019_EHard.csv" "Kar2019_EHard.jpg"

python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "Virat Parking 1 AP@.5" "Virat Parking 1 AP@.75" "Khirodkar2019" "Khirodkar2019_virat_p175.csv" "Khirodkar2019_virat_p175.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "Virat Parking 1 AP@.5" "Virat Parking 2 AP@.5" "Khirodkar2019" "Khirodkar2019_virat_p25.csv" "Khirodkar2019_viratp25.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "Virat Parking 1 AP@.5" "Virat Parking 2 AP@.75" "Khirodkar2019" "Khirodkar2019_viratp275.csv" "Khirodkar2019_viratp275.jpg
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "Virat Parking 1 AP@.5" "EPFL-CAR AP@.5" "Khirodkar2019" "Khirodkar2019_car5.csv" "Khirodkar2019_car5.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "Virat Parking 1 AP@.5" "EPFL-Car AP@.75" "Khirodkar2019" "Khirodkar2019_car75.csv" "Khirodkar2019_car75.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "Virat Parking 1 AP@.5" "UA-DETRAC Night AP@.5" "Khirodkar2019" "Khirodkar2019_detrac5.csv" "Khirodkar2019_detrac5.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "Virat Parking 1 AP@.5" "UA-DETRAC Night AP@.75" "Khirodkar2019" "Khirodkar2019_detrac75.csv" "Khirodkar2019_detrac75.jpg"

python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "Precision" "Madan2021" "Madan2021_precision.csv" "Madan2021_precision.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "Recycling" "Madan2021" "Madan2021_recycling.csv" "Madan2021_recycling.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "F0.3" "Madan2021" "Madan2021_f03.csv" "Madan2021_f03.jpg"

python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP-187" "mAP-50" "Mahmood2020" "Mahmood2020_map50.csv" "Mahmood2020_map50.jpg"

python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "person precision" "person recall" "Nowruzi2019" "Nowruzi2019_precall.csv" "Nowruzi2019_precall.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "person precision" "car precision" "Nowruzi2019" "Nowruzi2019_cprecision.csv" "Nowruzi2019_cprecision.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "person precision" "car recall" "Nowruzi2019" "Nowruzi2019_crecall.csv" "Nowruzi2019_crecall.jpg"

python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "aero" "Peng2015" "Peng2015_aero.csv" "Peng2015_aero.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "bike" "Peng2015" "Peng2015_bike.csv" "Peng2015_bike.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "boat" "Peng2015" "Peng2015_boat.csv" "Peng2015_boat.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "bottle" "Peng2015" "Peng2015_bott.csv" "Peng2015_bott.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "bus" "Peng2015" "Peng2015_bus.csv" "Peng2015_bus.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "car" "Peng2015" "Peng2015_car.csv" "Peng2015_car.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "cat" "Peng2015" "Peng2015_cat.csv" "Peng2015_cat.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "chair" "Peng2015" "Peng2015_chair.csv" "Peng2015_chair.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "cow" "Peng2015" "Peng2015_cow.csv" "Peng2015_cow.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "table" "Peng2015" "Peng2015_table.csv" "Peng2015_table.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "dog" "Peng2015" "Peng2015_dog.csv" "Peng2015_dog.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "horse" "Peng2015" "Peng2015_horse.csv" "Peng2015_horse.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "motorbike" "Peng2015" "Peng2015_motorbike.csv" "Peng2015_motorbike.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "person" "Peng2015" "Peng2015_person.csv" "Peng2015_person.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "plan" "Peng2015" "Peng2015_plan.csv" "Peng2015_plan.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "sheep" "Peng2015" "Peng2015_sheep.csv" "Peng2015_sheep.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "sofa" "Peng2015" "Peng2015_sofa.csv" "Peng2015_sofa.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "train" "Peng2015" "Peng2015_train.csv" "Peng2015_train.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "tv" "Peng2015" "Peng2015_tv.csv" "Peng2015_tv.jpg"

python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "100" "3.3" "Prakash2019" "Prakash2019_330.csv" "Prakash2019_330.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "100" "8.3" "Prakash2019" "Prakash2019_830.csv" "Prakash2019_830.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "100" "16.70" "Prakash2019" "Prakash2019_1670.csv" "Prakash2019_1670.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "100" "33.3" "Prakash2019" "Prakash2019_3330.csv" "Prakash2019_3330.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "100" "50" "Prakash2019" "Prakash2019_50.csv" "Prakash2019_50.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "100" "66.7" "Prakash2019" "Prakash2019_6670.csv" "Prakash2019_6670.jpg"

python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "mAP50" "Shermeyer2021" "Shermeyer2021_map50.csv" "Shermeyer2021_map50.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "AR" "Shermeyer2021" "Shermeyer2021_ar.csv" "Shermeyer2021_ar.jpg"

python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "Randomly initialized Weights" "ImageNet" "Tremblay2018" "Tremblay2018_imagenet.csv" "Tremblay2018_imagenet.jpg"

python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "Coca Cola" "Tripathi2019" "Tripathi2019_cocacola.csv" "Tripathi2019_cocacola.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "Coffeemate" "Tripathi2019" "Tripathi2019_coffeemate.csv" "Tripathi2019_coffeemate.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "Honey Bunches" "Tripathi2019" "Tripathi2019_honeybunches.csv" "Tripathi2019_honeybunches.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "Hunt's Sauce" "Tripathi2019" "Tripathi2019_huntsauce.csv" "Tripathi2019_huntsauce.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "Mahama Rice" "Tripathi2019" "Tripathi2019_mahamarice.csv" "Tripathi2019_mahamarice.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "nature v1" "Tripathi2019" "Tripathi2019_naturev1.csv" "Tripathi2019_naturev1.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "nature v2" "Tripathi2019" "Tripathi2019_naturev2.csv" "Tripathi2019_naturev2.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "Palmolive orange" "Tripathi2019" "Tripathi2019_palmoliveorange.csv" "Tripathi2019_palmoliveorange.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "pop secret" "Tripathi2019" "Tripathi2019_popsecret.csv" "Tripathi2019_popsecret.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "pringles bbq" "Tripathi2019" "Tripathi2019_pringlebbq.csv" "Tripathi2019_pringlebbq.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "Redbull" "Tripathi2019" "Tripathi2019_redbull.csv" "Tripathi2019_redbull.jpg"

python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "Accuracy" "Average Precision" "Wong2019" "Wong2019_AP.csv" "Wong2019_AP.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "Accuracy" "Average Recall" "Wong2019" "Wong2019_AR.csv" "Wong2019_AR.jpg"

python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "mAP@0.50" "Wrenninge2018" "Wrenninge2018_map50.csv" "Wrenninge2018_map50.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "mAP@0.75" "Wrenninge2018" "Wrenninge2018_map75.csv" "Wrenninge2018_map75.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "Car" "Wrenninge2018" "Wrenninge2018_car.csv" "Wrenninge2018_car.jpg"
python BMA_Dissertation.py "d:\rhugh\Documents\CTU_Doctoral\Dissertation\RawData.xlsx" "mAP" "Pedestrian" "Wrenninge2018" "Wrenninge2018_ped.csv" "Wrenninge2018_ped.jpg"